### ISSUE TITLE
Fix Google Forms wording

### ISSUE THREAD

**Issue by k4m4** [StCatsHacks/StCatsHacks-Website#3]
- `St. Cats Hacks Mailing List` --> `StCatsHacks Mailing List`
- `Keep updated on the current St Cats Hacks News` --> `Receive updates about the upcoming StCatsHacks hackathon`
- `Please type your FULL name` --> `Full Name`
*For future reference*: Please use descriptive commit names (e.g. instead of `Update index.html` for commit [80aeb7cc262988470b71b379dbb4216f7993203d](https://github.com/StCatsHacks/StCatsHacks-Website/commit/80aeb7cc262988470b71b379dbb4216f7993203d), use `Add Google Form Mailing List`)

**Comment by MrZisidis** [comment]
- StCatsHacks Mailing List -- done
- Wording fixed (StCatsHacks Mailing List, wording and "full name"
